### PR TITLE
prevent Unknown provider error when minified

### PR DESCRIPTION
**Pull request by gustavopaes**

### CODE REVIEW

**Comment by GuillaumeCisco** [comment]
Should be quickly merged !
Lost 2 hours of development due to this bug.

**Comment by williamboman** [comment]
@GuillaumeCisco Use my [fork](https://github.com/williamboman/angular-slugify). I've PR'd my changes but I don't see them ever being merged, I have registered a separate bower package as well (`wb-angular-slugify`).

**Comment by GuillaumeCisco** [comment]
Thanks @williamboman, I used @gustavopaes small modification that work correctly. I'll take a look to your repo in the week.

**Comment by paulsmith** [comment]
Thanks, fixed by a0f0991

**Pull request closed without merging**
